# 版本号
version: "3.8"

#定义服务
services:
  #具体的容器服务
  product-service:  # 需要启动的服务名称
    image: product-service  #使用的镜像
    ports:
      - 8081:8081      #指定端口映射

  order-service:  # 需要启动的服务名称
    image: order-service  #使用的镜像
    ports:
      - 8091:8091      #指定端口映射

  gateway-service:  # 需要启动的服务名称
    image: gateway-service  #使用的镜像
    ports:
      - 7000:7000      #指定端口映射