server:
  port: 8071
# spring 配置
spring:
  application:
    # 配置服务名称
    name: service-user
  # 配置数据源
  datasource:
    #  serverTimezone=UTC 解决数据库驱动版本过高而导致时区无法识别报错
    url: jdbc:mysql://192.168.172.3:3306/springcloud-alibaba?serverTimezone=UTC&useUnicode=true&CharacterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver