server:
  port: 8081
# spring 配置
spring:
  application:
    # 配置服务名称
    name: product-service
  # nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.172.3:8848
  # 配置数据源
  datasource:
    #  serverTimezone=UTC 解决数据库驱动版本过高而导致时区无法识别报错
    url: jdbc:mysql://192.168.172.3:3307/springcloudalibaba?serverTimezone=UTC&useUnicode=true&CharacterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml